filmorate:
  filmservice:
    count: 10

logging:
  level:
    org.zalando.logbook: TRACE

spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:h2:file:./db/filmorate
    username: mcat
    password: Inushing1980
    driverClassName: org.h2.Driver
